CREATE DATABASE IF NOT EXISTS presensi_qr;
USE presensi_qr;

CREATE TABLE IF NOT EXISTS kehadiran (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nama VARCHAR(100) NOT NULL,
  nim VARCHAR(20) NOT NULL UNIQUE,
  jurusan VARCHAR(100) NOT NULL,
  angkatan INT NOT NULL,
  waktu DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
